name: CI/CD CryptoDraw Development

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch: # This line adds support for manual triggering
    inputs:
      network:
        description: 'The network to deploy to'
        required: true
        default: 'sepolia'
        type: choice
        options:
          - sepolia
          - bsc_testnet
          - opBNB_testnet

jobs:
  setup:
    name: Setup and Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Set RPC URL
        id: set-rpc
        run: |
          case "${{ github.event.inputs.network }}" in
            "sepolia")
              echo "RPC_URL=${{ secrets.RPC_URL_SEPOLIA }}" >> $GITHUB_ENV
              ;;
            "bsc_testnet")
              echo "RPC_URL=${{ secrets.RPC_URL_BSC_TESTNET }}" >> $GITHUB_ENV
              ;;
            "opBNB_testnet")
              echo "RPC_URL=${{ secrets.RPC_URL_OPBNB_TESTNET }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Network '${{ github.event.inputs.network }}' not supported"
              exit 1
              ;;
          esac

      - name: Set NATIVE_TOKEN
        id: set-native-token
        run: |
          case "${{ github.event.inputs.network }}" in
            "sepolia")
              echo "NATIVE_TOKEN=${{ secrets.NATIVE_TOKEN_SEPOLIA }}" >> $GITHUB_ENV
              ;;
            "bsc_testnet")
              echo "NATIVE_TOKEN=${{ secrets.NATIVE_TOKEN_BSC_TESTNET }}" >> $GITHUB_ENV
              ;;
            "opBNB_testnet")
              echo "NATIVE_TOKEN=${{ secrets.NATIVE_TOKEN_OPBNB_TESTNET }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Network '${{ github.event.inputs.network }}' not supported"
              exit 1
              ;;
          esac

      - name: Debug Environment Variables
        run: |
          echo "RPC_URL=$RPC_URL"
          echo "NATIVE_TOKEN=$NATIVE_TOKEN"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npx hardhat test

  deploy:
    name: Deploy Contract
    runs-on: ubuntu-latest
    needs: [setup, test]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Check Required Environment Variables
        run: |
          if [ -z "$NATIVE_TOKEN" ] || [ -z "$RPC_URL" ] || [ -z "$PROJECT_FUNDS" ]; then
            echo "Missing required environment variables."
            exit 1
          fi

      - name: Run Deployment Script
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          NATIVE_TOKEN: ${{ env.NATIVE_TOKEN }}
          VRF_COORDINATOR_ADDRESS: ${{ secrets.VRF_COORDINATOR_ADDRESS }}
          KEY_HASH: ${{ secrets.KEY_HASH }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          PROJECT_FUNDS: ${{ secrets.PROJECT_FUNDS }}
          GRANT_FUND: ${{ secrets.GRANT_FUND }}
          OPERATION_FUND: ${{ secrets.OPERATION_FUND }}
          RPC_URL: ${{ env.RPC_URL }}
        run: npx hardhat run scripts/deploy.js --network ${{ github.event.inputs.network }}
