name: CI/CD CryptoDraw Development

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      network:
        description: 'The network to deploy to'
        required: true
        default: 'sepolia'
        type: choice
        options:
          - sepolia
          - bsc_testnet
          - opBNB_testnet

jobs:
  setup:
    name: Setup and Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Set RPC URL
        id: set-rpc
        run: |
          NETWORK=${{ github.event.inputs.network || 'sepolia' }}  # Default to 'sepolia' if not set
          case "$NETWORK" in
            "sepolia")
              echo "RPC_URL=${{ secrets.RPC_URL_SEPOLIA }}" >> $GITHUB_ENV
              ;;
            "bsc_testnet")
              echo "RPC_URL=${{ secrets.RPC_URL_BSC_TESTNET }}" >> $GITHUB_ENV
              ;;
            "opBNB_testnet")
              echo "RPC_URL=${{ secrets.RPC_URL_OPBNB_TESTNET }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Network '$NETWORK' not supported"
              exit 1
              ;;
          esac

      - name: Set NATIVE_TOKEN
        id: set-native-token
        run: |
          NETWORK=${{ github.event.inputs.network || 'sepolia' }}  # Default to 'sepolia' if not set
          case "$NETWORK" in
            "sepolia")
              echo "NATIVE_TOKEN=${{ secrets.NATIVE_TOKEN_SEPOLIA }}" >> $GITHUB_ENV
              ;;
            "bsc_testnet")
              echo "NATIVE_TOKEN=${{ secrets.NATIVE_TOKEN_BSC_TESTNET }}" >> $GITHUB_ENV
              ;;
            "opBNB_testnet")
              echo "NATIVE_TOKEN=${{ secrets.NATIVE_TOKEN_OPBNB_TESTNET }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Network '$NETWORK' not supported"
              exit 1
              ;;
          esac

      - name: Set Project and Fund Variables
        id: set-funds
        run: |
          NETWORK=${{ github.event.inputs.network || 'sepolia' }}  # Default to 'sepolia' if not set
          case "$NETWORK" in
            "sepolia")
              echo "PROJECT_FUND=${{ secrets.PROJECT_FUND_SEPOLIA }}" >> $GITHUB_ENV
              echo "GRANT_FUND=${{ secrets.GRANT_FUND_SEPOLIA }}" >> $GITHUB_ENV
              echo "OPERATION_FUND=${{ secrets.OPERATION_FUND_SEPOLIA }}" >> $GITHUB_ENV
              ;;
            "bsc_testnet")
              echo "PROJECT_FUND=${{ secrets.PROJECT_FUND_BSC_TESTNET }}" >> $GITHUB_ENV
              echo "GRANT_FUND=${{ secrets.GRANT_FUND_BSC_TESTNET }}" >> $GITHUB_ENV
              echo "OPERATION_FUND=${{ secrets.OPERATION_FUND_BSC_TESTNET }}" >> $GITHUB_ENV
              ;;
            "opBNB_testnet")
              echo "PROJECT_FUND=${{ secrets.PROJECT_FUND_OPBNB_TESTNET }}" >> $GITHUB_ENV
              echo "GRANT_FUND=${{ secrets.GRANT_FUND_OPBNB_TESTNET }}" >> $GITHUB_ENV
              echo "OPERATION_FUND=${{ secrets.OPERATION_FUND_OPBNB_TESTNET }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Network '$NETWORK' not supported"
              exit 1
              ;;
          esac

      - name: Debug Environment Variables
        run: |
          echo "RPC_URL=$RPC_URL"
          echo "NATIVE_TOKEN=$NATIVE_TOKEN"
          echo "PROJECT_FUND=$PROJECT_FUND"
          echo "GRANT_FUND=$GRANT_FUND"
          echo "OPERATION_FUND=$OPERATION_FUND"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npx hardhat test

  deploy:
    name: Deploy Contract
    runs-on: ubuntu-latest
    needs: [setup, test]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Check Required Environment Variables
        run: |
          if [ -z "$NATIVE_TOKEN" ] || [ -z "$RPC_URL" ] || [ -z "$PROJECT_FUND" ] || [ -z "$GRANT_FUND" ] || [ -z "$OPERATION_FUND" ]; then
            echo "Missing required environment variables."
            exit 1
          fi

      - name: Run Deployment Script
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          NATIVE_TOKEN: ${{ env.NATIVE_TOKEN }}
          PROJECT_FUND: ${{ env.PROJECT_FUND }}
          GRANT_FUND: ${{ env.GRANT_FUND }}
          OPERATION_FUND: ${{ env.OPERATION_FUND }}
          RPC_URL: ${{ env.RPC_URL }}
        run: npx hardhat run scripts/deploy.js --network ${{ github.event.inputs.network || 'sepolia' }}
