name: SuperSete HTML generator

on:
  workflow_run:
    workflows: ["SuperSete Auto Predict"]
    types:
      - completed

jobs:
  format-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install markdown2 jinja2

      - name: Gerar HTML formatado a partir de Markdown
        run: |
          python SuperSete/scripts/generate_html.py

      - name: Commit e push do HTML
        shell: bash
        run: |
          git config user.name "mzfshark"
          git config user.email "mzfshark@gmail.com"
          git add SuperSete/index.html
          if ! git diff --cached --quiet; then
            git commit -m "Atualiza apresentação HTML do Super Sete"
            git push
          else
            echo "Nenhuma mudança para comitar."
          fi

      - name: Publicar via GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./SuperSete
          publish_branch: gh-pages
          enable_jekyll: false
