name: SuperSete Auto Predict

on:
  push:
    paths:
      - 'SuperSete/data/SuperSete.csv'
  schedule:
    - cron: '0 12 * * *' # Executa diariamente às 9h BRT (12h UTC)
  workflow_dispatch:
  
jobs:
  predict-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install pandas numpy plotly

      - name: Rodar predição
        run: |
          python Oraculo/SuperSete/scripts/predict.py

      - name: Commit e push do relatório
        run: |
          git config user.name "mzfshark"
          git config user.email "mzfsharks@gmail.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Atualiza relatório Markdown do Super Sete"
            git push
          else
            echo "Nenhuma mudança para comitar."
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}


      - name: Publicar via GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./SuperSete/docs
          publish_branch: gh-pages
          enable_jekyll: true
