name: SuperSete Auto Predict

on:
  push:
    paths:
      - 'SuperSete/data/SuperSete.csv'
  schedule:
    - cron: '0 12 * * *' # Executa diariamente às 9h BRT (12h UTC)

jobs:
  predict-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install pandas numpy

      - name: Rodar predição
        run: |
          python SuperSete/predict.py

      - name: Commit e push do novo relatório (GitHub Pages)
        run: |
          git config --global user.email "mzfshark@gmail.com"
          git config --global user.name "mzfshark"
          git add SuperSete/index.html
          git commit -m "Atualiza relatório Super Sete"
          git push        
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Publicar via GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./SuperSete
          publish_branch: gh-pages
          enable_jekyll: false



